// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StuddyBot.Core.DAL.Data;

namespace StuddyBot.Core.Migrations
{
    [DbContext(typeof(StuddyBotContext))]
    [Migration("20190702103410_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.MyDialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dialog_number");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Time");

                    b.Property<string>("User_id");

                    b.HasKey("Id");

                    b.ToTable("Dialogs");
                });
#pragma warning restore 612, 618
        }
    }
}
