// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StuddyBot.Core.DAL.Data;

namespace StuddyBot.Core.Migrations
{
    [DbContext(typeof(StuddyBotContext))]
    [Migration("20190703050506_thirdMigration")]
    partial class thirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.Dialogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.MyDialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DialogId");

                    b.Property<int?>("DialogsId");

                    b.Property<string>("Message");

                    b.Property<string>("Sender");

                    b.Property<DateTimeOffset>("Time");

                    b.HasKey("Id");

                    b.HasIndex("DialogsId");

                    b.ToTable("Dialog");
                });

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.Dialogs", b =>
                {
                    b.HasOne("StuddyBot.Core.DAL.Entities.User", "User")
                        .WithMany("Dialogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("StuddyBot.Core.DAL.Entities.MyDialog", b =>
                {
                    b.HasOne("StuddyBot.Core.DAL.Entities.Dialogs", "Dialogs")
                        .WithMany("MyDialogs")
                        .HasForeignKey("DialogsId");
                });
#pragma warning restore 612, 618
        }
    }
}
